name: remend
description: >-
  A lightweight, zero-dependency library that intelligently completes
  incomplete Markdown syntax during streaming.
version: 0.0.1
repository: https://github.com/leynier/remend

environment:
  sdk: ^3.11.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
